# Generated by Django 5.0.6 on 2024-06-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado_civil_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='anio_nacimiento',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(default='Apellido Materno', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(default='Apellido Paterno', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dia_nacimiento',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='Estado', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mes_nacimiento',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(default='Municipio', max_length=100),
        ),
    ]
