# Generated by Django 5.0.6 on 2024-06-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='publicidad/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('posicion', models.CharField(choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha')], max_length=10)),
            ],
        ),
    ]
