# Generated by Django 5.0.6 on 2024-06-25 16:32

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_publicidad_posicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='Sin teléfono', max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d{3,4}$')]),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\d{16}$')]),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono'], name='clientes_cl_telefon_6177bc_idx'),
        ),
    ]
