# Generated by Django 5.0.6 on 2024-06-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_telefono_alter_tarjeta_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='posicion',
            field=models.CharField(choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha')], default='izquierda', max_length=10),
            preserve_default=False,
        ),
    ]
