# Generated by Django 5.0.6 on 2024-06-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_publicidad_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='posicion',
            field=models.CharField(choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha')], default='izquierda', max_length=10),
        ),
    ]
