from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('clientes/', views.clientes_list, name='clientes_list'),
    path('cliente/<int:id>/', views.cliente_detail, name='cliente_detail'),
    path('cliente/nuevo/', views.cliente_create, name='cliente_create'),
    path('cliente/<int:id>/editar/', views.cliente_update, name='cliente_update'),
    path('cliente/<int:id>/eliminar/', views.cliente_delete, name='cliente_delete'),
    path('registro_cliente/', views.registro_cliente, name='registro_cliente'),
    path('login_cliente/', views.login_cliente, name='login_cliente'),
    path('login_admin/', views.login_admin, name='login_admin'),
    path('logout_cliente/', views.logout_cliente, name='logout_cliente'),
    path('logout_admin/', views.logout_admin, name='logout_admin'),
    path('apuestas/', views.apuestas_list, name='apuestas_list'),
    path('apuesta/nueva/', views.apuesta_create, name='apuesta_create'),
    path('perfil/', views.perfil_cliente, name='perfil_cliente'),
    path('historial/', views.historial_apuestas, name='historial_apuestas'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('reporte/csv/', views.generar_reporte_csv, name='generar_reporte_csv'),
    path('reporte/excel/', views.generar_reporte_excel, name='generar_reporte_excel'),
    path('graficas/', views.graficas, name='graficas'),
    path('mis_apuestas/', views.mis_apuestas, name='mis_apuestas'),
    path('admin/users_management/', views.admin_user_list, name='admin_user_list'),
    path('admin/users_management/create/', views.admin_user_create, name='admin_user_create'),
    path('admin/users_management/<int:id>/edit/', views.admin_user_update, name='admin_user_update'),
    path('admin/users_management/<int:id>/delete/', views.admin_user_delete, name='admin_user_delete'),
    path('tarjeta/nueva/', views.agregar_tarjeta, name='agregar_tarjeta'),
    path('tarjetas/', views.listar_tarjetas_cliente, name='listar_tarjetas_cliente'),
    path('admin/tarjetas/', views.listar_tarjetas, name='listar_tarjetas'),
    path('tarjeta/<int:id>/editar/', views.editar_tarjeta, name='editar_tarjeta'),
    path('tarjeta/<int:id>/eliminar/', views.eliminar_tarjeta, name='eliminar_tarjeta'),
    path('publicidad/', views.lista_publicidad, name='lista_publicidad'),
    path('publicidad/nueva/', views.agregar_publicidad, name='agregar_publicidad'),
    path('publicidad/<int:id>/editar/', views.editar_publicidad, name='editar_publicidad'),
    path('publicidad/<int:id>/eliminar/', views.eliminar_publicidad, name='eliminar_publicidad')
]
